import BackgroundGradient from "@/components/custom_components/BackgroundGradient";
import HomeNavbar from "@/components/custom_components/HomeNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "KBC Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HomeNavbar />
      <BackgroundGradient />
      {children}
    </>
  );
}
